# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sslides',
                'doc_host': 'https://rleyvasal.github.io',
                'git_url': 'https://github.com/rleyvasal/sslides',
                'lib_path': 'sslides'},
  'syms': {'sslides.core': {'sslides.core.foo': ('core.html#foo', 'sslides/core.py')}}}
